Enhancement: Update symfony.lock when @dependabot updates dependencies

diff --git a/.github/workflows/integrate.yaml b/.github/workflows/integrate.yaml
--- a/.github/workflows/integrate.yaml
+++ b/.github/workflows/integrate.yaml
@@ -10,10 +10,87 @@ on: # yamllint disable-line rule:truthy
 
 env:
   APP_ENV: "test"
+  ERGEBNIS_BOT_EMAIL: "bot@ergebn.is"
   ERGEBNIS_BOT_NAME: "ergebnis-bot"
   PHP_EXTENSIONS: "mbstring"
 
 jobs:
+  symfony-flex:
+    name: "Symfony Flex"
+
+    runs-on: "ubuntu-latest"
+
+    strategy:
+      matrix:
+        php-version:
+          - "7.4"
+
+        dependencies:
+          - "locked"
+
+    steps:
+      - name: "Checkout"
+        uses: "actions/checkout@v2.3.2"
+        with:
+          ref: "${{ github.head_ref }}"
+          token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
+
+      - name: "Install PHP with extensions"
+        uses: "shivammathur/setup-php@2.4.3"
+        with:
+          coverage: "none"
+          extensions: "${{ env.PHP_EXTENSIONS }}"
+          php-version: "${{ matrix.php-version }}"
+
+      - name: "Determine composer cache directory"
+        uses: "./.github/actions/composer/composer/determine-cache-directory"
+
+      - name: "Cache dependencies installed with composer"
+        uses: "actions/cache@v2.1.1"
+        with:
+          path: "${{ env.COMPOSER_CACHE_DIR }}"
+          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
+          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
+
+      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
+        uses: "./.github/actions/composer/composer/install"
+        with:
+          dependencies: "${{ matrix.dependencies }}"
+
+      - name: "Synchronize symfony/flex recipes"
+        run: "composer symfony:sync-recipes"
+
+      - name: "Commit symfony.lock"
+        if: >
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.draft == false && (
+            github.event.action == 'opened' ||
+            github.event.action == 'reopened' ||
+            github.event.action == 'synchronize'
+          ) && (
+            (github.actor == 'dependabot[bot]' && startsWith(github.event.pull_request.title, 'composer(deps)')) ||
+            (github.actor == 'dependabot[bot]' && startsWith(github.event.pull_request.title, 'composer(deps-dev)'))
+          )
+        uses: "stefanzweifel/git-auto-commit-action@v4.4.1"
+        with:
+          branch: "${{ github.head_ref }}"
+          commit_author: "${{ env.ERGEBNIS_BOT_NAME }} <${{ env.ERGEBNIS_BOT_EMAIL }}>"
+          commit_message: "Fix: Update symfony.lock"
+          commit_user_email: "${{ env.ERGEBNIS_BOT_EMAIL }}"
+          commit_user_name: "${{ env.ERGEBNIS_BOT_NAME }}"
+          file_pattern: "symfony.lock"
+
+      - name: "Verify that symfony.lock is up-to-date"
+        if: "github.actor != 'dependabot[bot]'"
+        run: |
+          diff=$(git diff symfony.lock)
+
+          if [[ "${diff}" != "" ]]; then
+            echo "::error file=symfony.lock::symfony.lock is not up-to-date."
+
+            exit 1
+          fi
+
   coding-standards:
     name: "Coding Standards"
 
@@ -394,6 +471,7 @@ jobs:
       - "dependency-analysis"
       - "mutation-tests"
       - "static-code-analysis"
+      - "symfony-flex"
       - "tests"
 
     if: >
